"""Compact EPUB controls and discoverable reading panels, independent of loading."""
from commonUtils.ui import pyside as qt
from commonUtils.ui.reader_menus import ReaderMenus
from commonUtils.ui.reader_chrome import ReaderLabel, ReaderFullscreen, reader_button, READER_MARGINS, READER_SPACING
from .preferences import THEMES
from .text_view import BookText
from commonUtils.ui.read_aloud import ReadAloud, reader_text


def tool(page, action, name, icon=None):
    return reader_button(page, name, action=action, icon=icon)


def build_controls(page):
    layout = qt.QVBoxLayout(page)
    layout.setContentsMargins(*READER_MARGINS)
    layout.setSpacing(READER_SPACING)
    bar = page._external_menu_bar
    if bar is None:
        bar = qt.QMenuBar(page)
        bar.setNativeMenuBar(False)  # Embedded tabs must not replace Logistics's menus.
        layout.setMenuBar(bar)
    page.menus = ReaderMenus(page, bar, open_file=page.choose_book, open_path=page.open_book,
                             edit_metadata=page.edit_metadata, close=page.close_reader,
                             fullscreen=page.toggle_fullscreen, find=page.show_find,
                             open_label='Open EPUB…', suffixes=('.epub',))
    page.fullscreen = ReaderFullscreen(page, page.menus.fullscreen_action)
    page.sidebar_action = page.menus.action(page.menus.view, 'Show sidebar', page.toggle_sidebar, 'Ctrl+B', checkable=True)
    page.sidebar_action.setChecked(True)
    page.appearance_action = page.menus.action(page.menus.view, 'Reading appearance…', page.show_appearance)
    page.previous_action = page.menus.action(page.menus.navigate, 'Previous chapter', lambda: page.go_chapter(page._current - 1), 'Alt+Left')
    page.next_action = page.menus.action(page.menus.navigate, 'Next chapter', lambda: page.go_chapter(page._current + 1), 'Alt+Right')
    page.previous_page_action = page.menus.action(page.menus.navigate, 'Previous page', lambda: page.turn_page(-1))
    page.next_page_action = page.menus.action(page.menus.navigate, 'Next page', lambda: page.turn_page(1))
    page.go_page_action = page.menus.action(page.menus.navigate, 'Go to page…', page.go_to_page, 'Ctrl+G')
    page.add_bookmark_action = page.menus.action(page.menus.navigate, 'Add bookmark…', page.add_bookmark, 'Ctrl+D')
    page.menus.action(page.menus.navigate, 'Show bookmarks', page.show_bookmarks)
    header = qt.QHBoxLayout()
    header.setSpacing(READER_SPACING)
    page.open_button = tool(page, page.menus.open_action, 'Open EPUB')
    header.addWidget(page.open_button)
    page.previous = tool(page, page.previous_page_action, 'Previous page', 'previous')
    page.next = tool(page, page.next_page_action, 'Next page', 'next')
    page.title = ReaderLabel('EPUB reader')
    page.title.setAlignment(qt.Qt.AlignmentFlag.AlignCenter)
    page.title.setSizePolicy(qt.QSizePolicy.Policy.Ignored, qt.QSizePolicy.Policy.Preferred)
    header.addWidget(page.title, 1)
    header.addWidget(tool(page, page.sidebar_action, 'Show or hide contents and bookmarks', 'sidebar'))
    page.appearance_button = tool(page, page.appearance_action, 'Reading appearance', 'appearance')
    header.addWidget(page.appearance_button)
    page.fullscreen_button = tool(page, page.menus.fullscreen_action, 'Full screen', 'fullscreen')
    header.addWidget(page.fullscreen_button)
    layout.addLayout(header)
    # Retain the previous handle for callers without keeping another visible row.
    page.metadata_button = tool(page, page.menus.metadata_action, 'Edit metadata')
    page.metadata_button.hide()
    page.appearance = qt.QDialog(page, qt.Qt.WindowType.Popup)
    page.appearance.setWindowTitle('Reading appearance')
    form = qt.QFormLayout(page.appearance)
    form.setContentsMargins(16, 16, 16, 16)
    form.setHorizontalSpacing(16)
    form.setVerticalSpacing(12)
    page.font_family = qt.QFontComboBox()
    page.font_family.setCurrentFont(qt.QFont(page._settings['font_family']))
    page.font_family.currentFontChanged.connect(page._appearance_changed)
    page.font_family.setAccessibleName('Reading font')
    page.font_family.setMinimumHeight(32)
    form.addRow('Font', page.font_family)
    page.font_size = qt.QSpinBox()
    page.font_size.setRange(8, 48)
    page.font_size.setSuffix(' pt')
    page.font_size.setValue(page._settings['font_size'])
    page.font_size.valueChanged.connect(page._appearance_changed)
    page.font_size.setAccessibleName('Reading font size')
    page.font_size.setMinimumHeight(32)
    page.font_size.setKeyboardTracking(False)
    form.addRow('Text size', page.font_size)
    page.spacing = qt.QSpinBox()
    page.spacing.setRange(100, 220)
    page.spacing.setSingleStep(25)
    page.spacing.setSuffix('%')
    page.spacing.setValue(page._settings['line_spacing'])
    page.spacing.valueChanged.connect(page._appearance_changed)
    page.spacing.setAccessibleName('Line spacing')
    page.spacing.setMinimumHeight(32)
    page.spacing.setKeyboardTracking(False)
    form.addRow('Line spacing', page.spacing)
    page.reading_width = qt.QSpinBox()
    page.reading_width.setRange(480, 1400)
    page.reading_width.setSuffix(' px')
    page.reading_width.setValue(page._settings['reading_width'])
    page.reading_width.valueChanged.connect(page._appearance_changed)
    page.reading_width.setAccessibleName('Maximum reading width')
    page.reading_width.setMinimumHeight(32)
    page.reading_width.setKeyboardTracking(False)
    form.addRow('Reading width', page.reading_width)
    page.theme = qt.QComboBox()
    for name in THEMES:
        page.theme.addItem(name.title(), name)
    page.theme.setCurrentIndex(page.theme.findData(page._settings['theme']))
    page.theme.currentIndexChanged.connect(page._appearance_changed)
    page.theme.setAccessibleName('Reading theme')
    page.theme.setMinimumHeight(32)
    form.addRow('Theme', page.theme)
    page.splitter = qt.QSplitter()
    page.splitter.setChildrenCollapsible(False)
    page.sidebar = qt.QTabWidget()
    page.sidebar.setMinimumWidth(170)
    page.sidebar.setMaximumWidth(420)
    page.chapters = qt.QTreeWidget()
    page.chapters.setHeaderHidden(True)
    page.chapters.setAccessibleName('Book table of contents')
    page.chapters.itemClicked.connect(page._chapter_selected)
    page.chapters.itemActivated.connect(page._chapter_selected)
    page.sidebar.addTab(page.chapters, 'Contents')
    bookmarks_panel = qt.QWidget()
    bookmarks_layout = qt.QVBoxLayout(bookmarks_panel)
    bookmarks_layout.setContentsMargins(8, 8, 8, 8)
    bookmarks_layout.setSpacing(8)
    page.bookmark_list = qt.QListWidget()
    page.bookmark_list.setAccessibleName('Bookmarked places')
    page.bookmark_list.itemActivated.connect(lambda item: page.open_bookmark(page.bookmark_list.row(item)))
    page.bookmark_list.itemClicked.connect(lambda item: page.open_bookmark(page.bookmark_list.row(item)))
    bookmarks_layout.addWidget(page.bookmark_list, 1)
    bookmark_buttons = qt.QHBoxLayout()
    page.bookmark_button = qt.QPushButton('Add…')
    page.bookmark_button.clicked.connect(page.add_bookmark)
    page.remove_bookmark = qt.QPushButton('Remove')
    page.remove_bookmark.clicked.connect(page.delete_bookmark)
    bookmark_buttons.addWidget(page.bookmark_button)
    bookmark_buttons.addWidget(page.remove_bookmark)
    bookmarks_layout.addLayout(bookmark_buttons)
    page.bookmarks = qt.QComboBox(page)  # Compatibility handle; list is the visible control.
    page.bookmarks.hide()
    page.bookmarks.activated.connect(page.open_bookmark)
    page.sidebar.addTab(bookmarks_panel, 'Bookmarks')
    page.splitter.addWidget(page.sidebar)
    page.reading_area = qt.QWidget()
    reading_layout = qt.QHBoxLayout(page.reading_area)
    reading_layout.setContentsMargins(0, 0, 0, 0)
    page.text = BookText()
    page.speech = ReadAloud(page, lambda: reader_text(page.text, start=page.text.location()),
                            scope='the current chapter from this page')
    page.menus.view.addAction(page.speech.action)
    header.addWidget(reader_button(page, 'Read aloud', action=page.speech.action, text='Read aloud'))
    page.text.textChanged.connect(page.speech.stop)
    page.text.setMaximumWidth(page.reading_width.value())
    page.text.anchorClicked.connect(page._link_clicked)
    page.text.verticalScrollBar().valueChanged.connect(page._position_changed)
    page.text.pageTurn.connect(page.turn_page)
    page.text.paginationChanged.connect(page._position_changed)
    reading_layout.addWidget(page.text, 1)
    page.empty_panel = qt.QWidget()
    empty = qt.QVBoxLayout(page.empty_panel)
    empty.setContentsMargins(32, 32, 32, 32)
    empty.setSpacing(16)
    empty.addStretch()
    heading = qt.QLabel('EPUB reader')
    heading.setAlignment(qt.Qt.AlignmentFlag.AlignCenter)
    font = heading.font()
    font.setPointSizeF(max(18, font.pointSizeF() * 1.6))
    font.setBold(True)
    heading.setFont(font)
    empty.addWidget(heading)
    hint = qt.QLabel('Open a book, choose a chapter, and turn pages with the arrow keys.\n'
                     'Adjust the font and theme with Reading appearance.')
    hint.setAlignment(qt.Qt.AlignmentFlag.AlignCenter)
    hint.setWordWrap(True)
    hint.setForegroundRole(qt.QPalette.ColorRole.PlaceholderText)
    empty.addWidget(hint)
    page.empty_open = qt.QPushButton('Open EPUB…')
    page.empty_open.clicked.connect(page.choose_book)
    empty.addWidget(page.empty_open, 0, qt.Qt.AlignmentFlag.AlignHCenter)
    empty.addStretch()
    reading_layout.addWidget(page.empty_panel, 1)
    page.text.hide()
    page.splitter.addWidget(page.reading_area)
    page.splitter.setStretchFactor(1, 1)
    page.splitter.setSizes([240, 900])
    layout.addWidget(page.splitter, 1)
    page.find_panel = qt.QWidget()
    search = qt.QHBoxLayout(page.find_panel)
    search.setContentsMargins(0, 0, 0, 0)
    page.query = qt.QLineEdit()
    page.query.setPlaceholderText('Find in this chapter…')
    page.query.setClearButtonEnabled(True)
    page.query.returnPressed.connect(page.find_next)
    search.addWidget(page.query, 1)
    find = qt.QPushButton('Find next')
    find.clicked.connect(page.find_next)
    search.addWidget(find)
    dismiss = reader_button(page, 'Close search', icon='close')
    dismiss.clicked.connect(page.hide_find)
    search.addWidget(dismiss)
    escape = qt.QShortcut(qt.QKeySequence('Esc'), page)
    escape.setContext(qt.Qt.ShortcutContext.WidgetWithChildrenShortcut)
    escape.activated.connect(page.dismiss_overlay)
    layout.addWidget(page.find_panel)
    page.find_panel.hide()
    footer = qt.QHBoxLayout()
    footer.setSpacing(READER_SPACING)
    footer.addWidget(page.previous)
    footer.addWidget(page.next)
    page.status = ReaderLabel('Open an EPUB to start reading.', muted=True)
    footer.addWidget(page.status, 1)
    page.progress_label = qt.QLabel()
    page.progress_label.setAccessibleName('Reading progress')
    page.progress_label.setAlignment(qt.Qt.AlignmentFlag.AlignRight | qt.Qt.AlignmentFlag.AlignVCenter)
    footer.addWidget(page.progress_label)
    layout.addLayout(footer)
